apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: llm-gpu-training-lab
  title: llm-gpu-training-lab
  description: Hands-on lab teaching large language model fine-tuning using PyTorch
    on GPU-accelerated OpenShift infrastructure
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp-published
    ph.rhdp.io/github-user: treddy08
    ph.rhdp.io/owner: treddy@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/llm-gpu-training-lab
  tags:
  - publishing-house
  - lab
  - rhdp-published
  links:
  - url: https://github.com/rhpds/llm-gpu-training-lab
    title: Repository
    icon: github
  - url: https://devspaces.apps.ocpv-infra01.dal12.infra.demo.redhat.com#https://github.com/rhpds/llm-gpu-training-lab
    title: Open in DevSpaces
    icon: catalog
  - url: https://central-api-publishing-house.apps.ocpv-infra01.dal12.infra.demo.redhat.com
    title: Central
    icon: dashboard
  - url: https://redhat.atlassian.net/browse/RHDPCD-2012
    title: Jira Epic
    icon: bugs
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
